apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/general
    server: fs-07065285c35e3243.efs.ap-south-1.amazonaws.com
